server:
  port: 1106
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=utf-8
    username: root
    password: wxy123456
    hikari:
      auto-commit: true
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 100  #连接池最大连接数（使用负值表示没有限制）
        max-wait: 1      #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10     #连接池中的最大空闲连接
        min-idle: 0      #连接池中的最小空闲连接
    timeout: 1000        #连接超时时间毫秒